# Generated by Django 5.0.6 on 2026-07-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Customer email address for payment receipt', max_length=254),
        ),
    ]
