# Generated by Django 5.0.6 on 2026-07-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_fulfillment_type_alter_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_special_message',
            field=models.TextField(blank=True, default='', help_text='Optional message for the package (e.g., leave with receptionist)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default='', help_text='Exact location and a landmark'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, help_text='Customer email address for payment receipt', max_length=254),
        ),
    ]
